# Generated by Django 5.2.6 on 2025-10-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_userprofile_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stallapplication',
            name='email',
            field=models.EmailField(default='default', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
