# Generated by Django 5.2.6 on 2025-10-28 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_customuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stallapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.customuserprofile'),
        ),
        migrations.RemoveField(
            model_name='stallapplication',
            name='email',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
