# Generated by Django 5.2.6 on 2025-10-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_stallapplication_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='role',
            field=models.CharField(choices=[('DC', 'District Commissioner'), ('HOD_FIRE', 'HOD - Fire Department'), ('HOD_REDCROSS', 'HOD - Red Cross'), ('HOD_POLICE', 'HOD - Police Department'), ('USER', 'Regular User')], default='USER', max_length=20),
        ),
    ]
