# Generated by Django 5.2.6 on 2025-10-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_customuserprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='stallapplication',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
