# Generated by Django 5.2.6 on 2025-10-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_stallapplication_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='stallapplication',
            name='dc_approval_doc',
            field=models.FileField(blank=True, null=True, upload_to='approvals/dc/'),
        ),
        migrations.AddField(
            model_name='stallapplication',
            name='dc_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stallapplication',
            name='hod_fire_approval_doc',
            field=models.FileField(blank=True, null=True, upload_to='approvals/fire/'),
        ),
        migrations.AddField(
            model_name='stallapplication',
            name='hod_fire_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stallapplication',
            name='hod_police_approval_doc',
            field=models.FileField(blank=True, null=True, upload_to='approvals/police/'),
        ),
        migrations.AddField(
            model_name='stallapplication',
            name='hod_police_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stallapplication',
            name='hod_redcross_approval_doc',
            field=models.FileField(blank=True, null=True, upload_to='approvals/redcross/'),
        ),
        migrations.AddField(
            model_name='stallapplication',
            name='hod_redcross_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
