# Generated by Django 5.2.6 on 2025-11-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_stallapplication_hod_fire_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stallapplication',
            name='hod_fire_status',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='stallapplication',
            name='hod_police_status',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='stallapplication',
            name='hod_redcross_status',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='stallapplication',
            name='status',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Fresh', max_length=20),
        ),
    ]
