# Generated by Django 5.2.6 on 2025-11-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_stallapplication_hod_fire_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stallapplication',
            name='dc_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stallapplication',
            name='hod_fire_status',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='stallapplication',
            name='hod_police_status',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='stallapplication',
            name='hod_redcross_status',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='stallapplication',
            name='status',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Fresh', max_length=20),
        ),
    ]
