# Generated by Django 5.2.6 on 2025-11-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_stallapplication_dc_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stallapplication',
            name='hod_fire_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stallapplication',
            name='hod_police_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stallapplication',
            name='hod_redcross_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
