# Generated by Django 5.2.6 on 2025-11-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_stallapplication_hod_fire_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stallapplication',
            name='dc_forwarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
